/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinySplit: typeof import('@opentiny/vue')['Split']
    TinyTabItem: typeof import('@opentiny/vue')['TabItem']
    TinyTabs: typeof import('@opentiny/vue')['Tabs']
  }
}
